channels:
- bioconda
- conda-forge
- defaults
dependencies:
- r-arrow=3.0.0
- r-askpass=1.1
- r-base64enc=0.1_3
- r-base=3.5.1
- r-biocmanager
- r-bit64=0.9_7
- r-bit=1.1_15.2
- r-callr=3.4.3
- r-cli=2.0.2
- r-codetools=0.2_16
- r-colorspace=1.4_1
- r-curl=4.3
- r-data.table=1.11.6
- r-generics=0.0.2
- r-ggplot2=3.3.0
- r-htmltools=0.4.0
- r-htmlwidgets=1.5.1
- r-httpuv=1.5.2
- r-httr=1.4.1
- r-knitr=1.28
- r-lambda.r=1.2.4
- r-mass=7.3_51.6
- r-matrix=1.2_18
- r-openssl=1.4.1
- r-pheatmap=1.0.12
- r-pkgbuild=1.0.7
- r-pkgconfig
- r-pkgload=1.0.2
- r-png=0.1_7
- r-progress=1.2.2
- r-purrr=0.3.4
- r-renv
- r-renv=0.9.3
- r-rjson=0.2.20
- r-rlang
- r-rmarkdown=2.1
- r-rsqlite=2.2.0
- r-scales=1.1.0
- r-svglite=1.2.3
- r-sys=3.3
- r-unix
- r-utf8=1.1.4
- r-xml2=1.3.2
- r-xml=3.99_0.3
- r-yaml=2.2.1
name: bulk_rna_seq
