channels:
- bioconda
- conda-forge
- defaults
dependencies:
- r-arrow
- r-askpass
- r-base64enc=0.1_3
- r-base=3.5.1
- r-biocmanager
- r-bit
- r-bit64
- r-callr
- r-cli
- r-codetools
- r-colorspace
- r-curl
- r-data.table
- r-generics
- r-ggplot2
- r-htmltools
- r-htmlwidgets
- r-httpuv
- r-httr
- r-knitr
- r-lambda.r
- r-mass
- r-matrix
- r-openssl
- r-pheatmap
- r-pkgbuild
- r-pkgconfig
- r-pkgload
- r-png
- r-progress
- r-purrr
- r-renv
- r-renv
- r-rjson
- r-rlang
- r-rmarkdown
- r-rsqlite
- r-scales
- r-svglite
- r-sys
- r-unix
- r-utf8
- r-xml
- r-xml2
- r-yaml
name: bulk_rna_seq
