channels:
- bioconda
- conda-forge
- defaults
dependencies:
- bioconductor-annotate=1.60.1
- bioconductor-annotationdbi=1.44.0
- bioconductor-biobase=2.42.0
- bioconductor-biocgenerics=0.28.0
- bioconductor-biocparallel=1.16.6
- bioconductor-complexheatmap=2.0.0
- bioconductor-edger=3.24.3
- bioconductor-fgsea=1.8.0
- bioconductor-genefilter=1.64.0
- bioconductor-genomeinfodbdata=1.2.1
- bioconductor-iranges=2.16.0
- bioconductor-limma=3.38.3
- bioconductor-s4vectors=0.20.1
- bioconductor-sva=3.30.1
name: buil_rna_seq
