channels:
- bioconda
- conda-forge
- defaults
dependencies:
- bioconductor-affy=1.60.0
- bioconductor-affyio=1.52.0
- bioconductor-all=1.24.0
- bioconductor-annotate=1.60.1
- bioconductor-annotationdbi=1.44.0
- bioconductor-annotationfilter=1.6.0
- bioconductor-annotationforge=1.24.0
- bioconductor-apeglm=1.4.1
- bioconductor-aroma.light=3.12.0
- bioconductor-beachmat=1.4.0
- bioconductor-biobase=2.42.0
- bioconductor-biocgenerics=0.28.0
- bioconductor-biocneighbors=1.0.0
- bioconductor-biocparallel=1.16.6
- bioconductor-biocviews=1.50.9
- bioconductor-biomart=2.38.0
- bioconductor-biomformat=1.10.1
- bioconductor-biostrings=2.50.2
- bioconductor-biovizbase=1.30.1
- bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.0
- bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.1
- bioconductor-bsgenome=1.50.0
- bioconductor-category=2.48.0
- bioconductor-complexheatmap=1.20.0
- bioconductor-consensusclusterplus=1.46.0
- bioconductor-delayedarray=0.8.0
- bioconductor-delayedmatrixstats=1.4.0
- bioconductor-deseq2=1.22.1
- bioconductor-deseq=1.34.1
- bioconductor-diffbind=2.10.0
- bioconductor-dropletutils=1.2.1
- bioconductor-edaseq=2.16.0
- bioconductor-edger=3.24.3
- bioconductor-ensembldb=2.6.3
- bioconductor-fgsea=1.8.0
- bioconductor-genefilter=1.64.0
- bioconductor-geneplotter=1.60.0
- bioconductor-genomeinfodb=1.18.1
- bioconductor-genomeinfodbdata=1.2.1
- bioconductor-genomicalignments=1.18.1
- bioconductor-genomicdatacommons=1.6.0
- bioconductor-genomicfeatures=1.34.1
- bioconductor-genomicranges=1.34.0
- bioconductor-ggtree=1.16.0
- bioconductor-go.db=3.7.0
- bioconductor-gostats=2.48.0
- bioconductor-graph=1.60.0
- bioconductor-gseabase=1.44.0
- bioconductor-gsva=1.30.0
- bioconductor-gviz=1.26.4
- bioconductor-hdf5array=1.10.1
- bioconductor-hsmmsinglecell=1.2.0
- bioconductor-impute=1.58.0
- bioconductor-interactionset=1.10.0
- bioconductor-iranges=2.16.0
- bioconductor-ivygapse=1.4.0
- bioconductor-limma=3.38.3
- bioconductor-maftools=2.4.12
- bioconductor-mast=1.8.1
- bioconductor-monocle=2.10.0
- bioconductor-msa=1.14.0
- bioconductor-multtest=2.38.0
- bioconductor-mutationalpatterns=1.8.0
- bioconductor-netbiov=1.18.0
- bioconductor-omiccircos=1.20.0
- bioconductor-org.hs.eg.db=3.7.0
- bioconductor-org.mm.eg.db=3.7.0
- bioconductor-phyloseq=1.26.1
- bioconductor-preprocesscore=1.44.0
- bioconductor-protgenerics=1.14.0
- bioconductor-pvca=1.22.0
- bioconductor-rbgl=1.58.2
- bioconductor-rgraphviz=2.26.0
- bioconductor-rhdf5=2.26.2
- bioconductor-rhdf5lib=1.4.3
- bioconductor-rsamtools=1.34.0
- bioconductor-rtracklayer=1.42.1
- bioconductor-s4vectors=0.20.1
- bioconductor-scater=1.10.1
- bioconductor-scran=1.10.1
- bioconductor-shortread=1.40.0
- bioconductor-singlecellexperiment=1.4.0
- bioconductor-singscore=1.2.2
- bioconductor-summarizedexperiment=1.12.0
- bioconductor-sva=3.30.1
- bioconductor-synergyfinder=1.10.0
- bioconductor-systempiper=1.16.0
- bioconductor-tcgabiolinks=2.14.0
- bioconductor-trackviewer=1.18.0
- bioconductor-treeio=1.8.0
- bioconductor-variancepartition=1.12.3
- bioconductor-variantannotation=1.28.3
- bioconductor-vsn=3.50.0
- bioconductor-xvector=0.22.0
- bioconductor-zlibbioc=1.28.0
name: legacy
