channels:
- bioconda
- conda-forge
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- _r-mutex=1.0.1
- abseil-cpp=20200225.2
- appdirs=1.4.4
- arpack=3.7.0
- arriba=1.2.0
- arrow-cpp=3.0.0
- binutils_impl_linux-64=2.34
- binutils_linux-64=2.34
- bioconductor-affy=1.60.0
- bioconductor-affyio=1.52.0
- bioconductor-all=1.24.0
- bioconductor-annotate=1.60.1
- bioconductor-annotationdbi=1.44.0
- bioconductor-annotationfilter=1.6.0
- bioconductor-annotationforge=1.24.0
- bioconductor-apeglm=1.4.1
- bioconductor-aroma.light=3.12.0
- bioconductor-beachmat=1.4.0
- bioconductor-biobase=2.42.0
- bioconductor-biocgenerics=0.28.0
- bioconductor-biocneighbors=1.0.0
- bioconductor-biocparallel=1.16.6
- bioconductor-biocviews=1.50.9
- bioconductor-biomart=2.38.0
- bioconductor-biomformat=1.10.1
- bioconductor-biostrings=2.50.2
- bioconductor-biovizbase=1.30.1
- bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.0
- bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.1
- bioconductor-bsgenome=1.50.0
- bioconductor-category=2.48.0
- bioconductor-complexheatmap=1.20.0
- bioconductor-consensusclusterplus=1.46.0
- bioconductor-delayedarray=0.8.0
- bioconductor-delayedmatrixstats=1.4.0
- bioconductor-deseq2=1.22.1
- bioconductor-deseq=1.34.1
- bioconductor-diffbind=2.10.0
- bioconductor-dropletutils=1.2.1
- bioconductor-edaseq=2.16.0
- bioconductor-edger=3.24.3
- bioconductor-ensembldb=2.6.3
- bioconductor-fgsea=1.8.0
- bioconductor-genefilter=1.64.0
- bioconductor-geneplotter=1.60.0
- bioconductor-genomeinfodb=1.18.1
- bioconductor-genomeinfodbdata=1.2.1
- bioconductor-genomicalignments=1.18.1
- bioconductor-genomicdatacommons=1.6.0
- bioconductor-genomicfeatures=1.34.1
- bioconductor-genomicranges=1.34.0
- bioconductor-ggtree=1.16.0
- bioconductor-go.db=3.7.0
- bioconductor-gostats=2.48.0
- bioconductor-graph=1.60.0
- bioconductor-gseabase=1.44.0
- bioconductor-gsva=1.30.0
- bioconductor-gviz=1.26.4
- bioconductor-hdf5array=1.10.1
- bioconductor-hsmmsinglecell=1.2.0
- bioconductor-impute=1.58.0
- bioconductor-interactionset=1.10.0
- bioconductor-iranges=2.16.0
- bioconductor-ivygapse=1.4.0
- bioconductor-limma=3.38.3
- bioconductor-maftools=2.4.12
- bioconductor-mast=1.8.1
- bioconductor-monocle=2.10.0
- bioconductor-msa=1.14.0
- bioconductor-multtest=2.38.0
- bioconductor-mutationalpatterns=1.8.0
- bioconductor-netbiov=1.18.0
- bioconductor-omiccircos=1.20.0
- bioconductor-org.hs.eg.db=3.7.0
- bioconductor-org.mm.eg.db=3.7.0
- bioconductor-phyloseq=1.26.1
- bioconductor-preprocesscore=1.44.0
- bioconductor-protgenerics=1.14.0
- bioconductor-pvca=1.22.0
- bioconductor-rbgl=1.58.2
- bioconductor-rgraphviz=2.26.0
- bioconductor-rhdf5=2.26.2
- bioconductor-rhdf5lib=1.4.3
- bioconductor-rsamtools=1.34.0
- bioconductor-rtracklayer=1.42.1
- bioconductor-s4vectors=0.20.1
- bioconductor-scater=1.10.1
- bioconductor-scran=1.10.1
- bioconductor-shortread=1.40.0
- bioconductor-singlecellexperiment=1.4.0
- bioconductor-singscore=1.2.2
- bioconductor-summarizedexperiment=1.12.0
- bioconductor-sva=3.30.1
- bioconductor-synergyfinder=1.10.0
- bioconductor-systempiper=1.16.0
- bioconductor-tcgabiolinks=2.14.0
- bioconductor-trackviewer=1.18.0
- bioconductor-treeio=1.8.0
- bioconductor-variancepartition=1.12.3
- bioconductor-variantannotation=1.28.3
- bioconductor-vsn=3.50.0
- bioconductor-xvector=0.22.0
- bioconductor-zlibbioc=1.28.0
- biothings_client=0.2.6
- blas=2.10
- boost-cpp=1.73.0
- boost=1.73.0
- brotli-bin=1.0.9
- brotli=1.0.9
- brotlipy=0.7.0
- bwidget=1.9.14
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2022.9.24
- cairo=1.16.0
- certifi=2021.5.30
- cffi=1.14.6
- charset-normalizer=2.1.1
- cloudpickle=2.2.0
- colorama=0.4.5
- colormath=3.0.0
- conjure-python-client=1.10.1
- cryptography=35.0.0
- curl=7.68.0
- cycler=0.11.0
- cytoolz=0.11.0
- dask-core=2021.3.1
- dbus=1.13.18
- decorator=4.4.2
- deeptools=3.5.1
- deeptoolsintervals=0.1.9
- dill=0.3.5.1
- double-conversion=3.2.0
- editdistance=0.5.3
- expat=2.5.0
- font-ttf-dejavu-sans-mono=2.37
- fontconfig=2.14.1
- freetype=2.12.1
- frobjects=0.3.2
- future=0.18.2
- gcc_impl_linux-64=7.3.0
- gcc_linux-64=7.3.0
- gettext=0.21.1
- gflags=2.2.2
- gfortran_impl_linux-64=7.3.0
- gfortran_linux-64=7.3.0
- giflib=5.2.1
- glib-tools=2.74.1
- glib=2.74.1
- glog=0.5.0
- glpk=4.65
- gmp=6.2.1
- graphite2=1.3.14
- graphviz=2.40.1
- grpc-cpp=1.29.0
- gsl=2.5
- gst-plugins-base=1.14.0
- gstreamer=1.14.0
- gxx_impl_linux-64=7.3.0
- gxx_linux-64=7.3.0
- harfbuzz=2.8.1
- hdf5=1.10.5
- htslib=1.9
- icu=58.2
- idna=3.4
- igraph=0.9.2
- imageio=2.13.1
- inchi=1.05
- jedi=0.17.2
- joblib=1.2.0
- jpeg=9e
- kiwisolver=1.3.1
- krb5=1.16.4
- lcms2=2.12
- ld_impl_linux-64=2.34
- libblas=3.8.0
- libboost=1.73.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.8.0
- libcurl=7.68.0
- libdeflate=1.5
- libedit=3.1.20210910
- libevent=2.1.12
- libffi=3.4.2
- libgcc-ng=12.1.0
- libgcc=7.2.0
- libgfortran-ng=7.5.0
- libgfortran4=7.5.0
- libglib=2.74.1
- libglu=9.0.0
- libgomp=12.1.0
- libiconv=1.17
- libidn2=2.3.4
- liblapack=3.8.0
- liblapacke=3.8.0
- libllvm9=9.0.1
- libopenblas=0.3.18
- libpng=1.6.38
- libprotobuf=3.11.4
- libssh2=1.8.2
- libstdcxx-ng=12.1.0
- libthrift=0.13.0
- libtiff=4.2.0
- libtool=2.4.6
- libunistring=0.9.10
- libuuid=2.32.1
- libwebp-base=1.2.2
- libwebp=1.2.2
- libxcb=1.15
- libxml2=2.9.14
- libzlib=1.2.13
- llvmlite=0.33.0
- lz4-c=1.9.3
- make=4.3
- matplotlib-base=3.3.4
- matplotlib=2.2.3
- metis=5.1.0
- mordred=1.2.0
- mpfr=4.1.0
- mygene=3.2.2
- ncurses=6.3
- networkx=2.5.1
- numba=0.50.1
- numpy=1.19.5
- olefile=0.46
- omero-py=5.10.3
- openblas=0.3.6
- openssl=1.1.1
- opentsne=0.6.0
- orc=1.6.5
- packaging=21.3
- pandas=0.25.3
- pandoc=2.16.2
- pango=1.40.14
- parso=0.7.1
- pcre2=10.40
- pcre=8.45
- pillow=8.3.1
- pip=22.0.2
- pixman=0.38.0
- plotly=4.14.3
- py-boost=1.73.0
- py2bit=0.3.0
- py4j=0.10.9.7
- pyarrow=3.0.0
- pybigwig=0.3.17
- pycairo=1.20.1
- pycparser=2.21
- pykerberos=1.2.1
- pyopenssl=22.0.0
- pyparsing=3.0.9
- pyqt=5.9.2
- pysam=0.15.4
- pysocks=1.7.1
- python-dateutil=2.8.2
- python-file-paths=0.0.10
- python=3.6.10
- python_abi=3.6
- pytz=2022.6
- pywavelets=1.1.1
- pyyaml=5.4.1
- qt=5.9.7
- qtl2=0.20
- r-abind=1.4_5
- r-acepack=1.4.1
- r-ade4=1.7_15
- r-amap=0.8_16
- r-ape=5.3
- r-arrow=3.0.0
- r-ashr=2.2_47
- r-askpass=1.1
- r-assertthat=0.2.1
- r-backports=1.2.1
- r-base64enc=0.1_3
- r-base=3.5.1
- r-batchjobs=1.8
- r-bbmisc=1.11
- r-bbmle=1.0.23.1
- r-bdsmatrix=1.3_4
- r-beeswarm=0.2.3
- r-bh=1.72.0_3
- r-bibtex=0.4.2.2
- r-bigl=1.2.3
- r-bio3d=2.4_1
- r-biocmanager
- r-biocmanager=1.30.10
- r-bit64=0.9_7
- r-bit=1.1_15.2
- r-bitops=1.0_6
- r-blob=1.2.1
- r-boot=1.3_25
- r-brew=1.0_6
- r-broom=0.5.6
- r-callr=3.4.3
- r-car=3.0_7
- r-cardata=3.0_3
- r-caret=6.0_86
- r-catools=1.17.1.4
- r-cellranger=1.1.0
- r-checkmate=2.0.0
- r-circlize=0.4.9
- r-class=7.3_17
- r-cli=3.4.1
- r-clipr=0.7.0
- r-cluster=2.1.0
- r-coda=0.19_3
- r-codetools=0.2_16
- r-colorramps=2.3
- r-colorspace=1.4_1
- r-colourpicker=1.0
- r-combinat=0.0_8
- r-cometexacttest=0.1.5
- r-commonmark=1.7
- r-corrplot=0.84
- r-covr=3.5.0
- r-cowplot=1.0.0
- r-crayon=1.3.4
- r-crosstalk=1.1.0.1
- r-curl=4.3
- r-data.table=1.12.8
- r-dbi=1.1.0
- r-dbplyr=1.4.3
- r-ddrtree=0.1.5
- r-dendextend=1.13.4
- r-dendsort=0.3.3
- r-densityclust=0.3
- r-deoptimr=1.0_8
- r-deriv=4.0
- r-desc=1.2.0
- r-desolve=1.28
- r-devtools=2.3.0
- r-dichromat=2.0_0
- r-digest=0.6.25
- r-docopt=0.6.1
- r-dofuture=0.9.0
- r-doparallel=1.0.15
- r-dotcall64=1.0_0
- r-downloader=0.4
- r-dplyr=0.8.5
- r-dppackage=1.1_7.4
- r-dqrng=0.2.1
- r-drc=3.0_1
- r-drugcombo=1.0.3
- r-dt=0.13
- r-dynamictreecut=1.63_1
- r-ellipsis=0.3.0
- r-emdbook=1.3.12
- r-etrunct=0.1
- r-evaluate=0.14
- r-exactranktests=0.8_31
- r-fansi=0.4.1
- r-farver=2.0.3
- r-fastcluster=1.1.25
- r-fastica=1.2_2
- r-fastmap=1.1.0
- r-fastmatch=1.1_0
- r-fields=10.3
- r-fit.models=0.5_14
- r-fitdistrplus=1.1_6
- r-fnn=1.1.3
- r-forcats=0.5.0
- r-foreach=1.5.0
- r-foreign=0.8_76
- r-formatr=1.7
- r-formula=1.2_3
- r-fs=1.5.2
- r-futile.logger=1.4.3
- r-futile.options=1.0.1
- r-future.apply=1.5.0
- r-future=1.17.0
- r-gbrd=0.4_11
- r-gdata=2.18.0
- r-gdtools=0.2.2
- r-geiger=2.0.6.4
- r-generics=0.0.2
- r-getoptlong=0.1.8
- r-ggally=1.5.0
- r-ggbeeswarm=0.6.0
- r-ggdendro=0.1_20
- r-ggextra=0.9
- r-ggforce=0.3.1
- r-ggfortify=0.4.10
- r-ggplot2=3.3.0
- r-ggpmisc=0.3.4
- r-ggpubr=0.2.5
- r-ggraph=2.0.2
- r-ggrepel=0.8.2
- r-ggridges=0.5.2
- r-ggsci=2.9
- r-ggsignif=0.6.0
- r-ggthemes=4.2.0
- r-gh=1.1.0
- r-git2r=0.26.1
- r-globaloptions=0.1.1
- r-globals=0.12.5
- r-glue=1.6.2
- r-gower=0.2.1
- r-gplots=3.0.3
- r-graphlayouts=0.7.0
- r-gridbase=0.4_7
- r-gridextra=2.3
- r-gridgraphics=0.5_0
- r-grimport=0.9_3
- r-gtable=0.3.0
- r-gtools=3.8.2
- r-harmony=1.0
- r-haven=2.2.0
- r-hdf5r=1.3.2
- r-hexbin=1.28.1
- r-highr=0.8
- r-hmisc=4.4_0
- r-hms=0.5.3
- r-htmltable=1.13.3
- r-htmltools=0.5.3
- r-htmlwidgets=1.5.1
- r-httpuv=1.5.2
- r-httr=1.4.1
- r-hwriter=1.3.2
- r-ica=1.0_2
- r-igraph=1.2.5
- r-ini=0.3.1
- r-invgamma=1.1
- r-ipred=0.9_9
- r-ips=0.0.11
- r-irlba=2.3.3
- r-isoband=0.2.1
- r-iterators=1.0.12
- r-jsonlite=1.6.1
- r-kernsmooth=2.23_17
- r-km.ci=0.5_2
- r-kmsurv=0.1_5
- r-knitr=1.28
- r-l2p=0.0_1
- r-labeling=0.3
- r-lambda.r=1.2.4
- r-later=1.0.0
- r-lattice=0.20_41
- r-latticeextra=0.6_28
- r-lava=1.6.7
- r-lazyeval=0.2.2
- r-leiden=0.3.3
- r-lifecycle=0.2.0
- r-listenv=0.8.0
- r-lme4=1.1_23
- r-lmertest=3.1_2
- r-lmtest=0.9_37
- r-locfit=1.5_9.4
- r-lubridate=1.7.8
- r-magrittr=2.0.3
- r-manipulatewidget=0.10.1
- r-maps=3.3.0
- r-maptools=0.9_9
- r-markdown=1.1
- r-mass=7.3_51.6
- r-matlab=1.0.2
- r-matrix=1.2_18
- r-matrixmodels=0.4_1
- r-matrixstats=0.56.0
- r-maxstat=0.7_25
- r-mclust=5.4.6
- r-memoise=1.1.0
- r-metap=1.1
- r-mgcv=1.8_31
- r-mime=0.9
- r-miniui=0.1.1.1
- r-minpack.lm=1.2_1
- r-minqa=1.2.4
- r-mixsqp=0.3_17
- r-modelmetrics=1.2.2.2
- r-modelr=0.1.7
- r-modes=0.7.0
- r-multcomp=1.4_13
- r-munsell=0.5.0
- r-mvtnorm=1.1_0
- r-ncbit=2013.03.29
- r-nleqslv=3.3.2
- r-nlme=3.1_147
- r-nloptr=1.2.2.1
- r-nmf=0.21.0
- r-nnet=7.3_14
- r-numderiv=2016.8_1.1
- r-openssl=1.4.1
- r-openxlsx=4.1.4
- r-outliers=0.14
- r-patchwork=1.0.0
- r-pbapply=1.4_2
- r-pbkrtest=0.4_7
- r-pbmcapply=1.5.0
- r-pcapp=1.9_73
- r-permute=0.9_5
- r-phangorn=2.5.5
- r-pheatmap=1.0.12
- r-pillar=1.4.3
- r-pixmap=0.4_11
- r-pkgbuild=1.0.7
- r-pkgconfig=2.0.3
- r-pkgload=1.0.2
- r-pkgmaker=0.31.1
- r-plogr=0.2.0
- r-plotly=4.9.2.1
- r-plotrix=3.7_8
- r-plyr=1.8.6
- r-png=0.1_7
- r-polyclip=1.10_0
- r-polynom=1.4_0
- r-pracma=2.2.9
- r-praise=1.0.0
- r-prettyunits=1.1.1
- r-proc=1.16.2
- r-processx=3.4.2
- r-prodlim=2019.11.13
- r-progress=1.2.2
- r-promises=1.1.0
- r-proxy=0.4_24
- r-pryr=0.1.4
- r-ps=1.3.2
- r-purrr=0.3.4
- r-qlcmatrix=0.9.7
- r-qtl=1.46_2
- r-quadprog=1.5_8
- r-quantmod=0.4.17
- r-quantreg=5.55
- r-r.methodss3=1.8.0
- r-r.oo=1.23.0
- r-r.utils=2.9.2
- r-r6=2.4.1
- r-randomforest=4.6_14
- r-rann=2.6.1
- r-rappdirs=0.3.1
- r-rcmdcheck=1.3.3
- r-rcolorbrewer=1.1_2
- r-rcpp=1.0.6
- r-rcppannoy=0.0.16
- r-rcpparmadillo=0.9.870.2.0
- r-rcppeigen=0.3.3.7.0
- r-rcppnumerical=0.4_0
- r-rcppparallel=5.1.5
- r-rcppprogress=0.4.2
- r-rcurl=1.98_1.2
- r-rdpack=0.11_1
- r-readr=1.3.1
- r-readxl=1.3.1
- r-recipes=0.1.12
- r-registry=0.5_1
- r-rematch2=2.1.2
- r-rematch=1.0.1
- r-remotes=2.1.1
- r-renv
- r-reprex=0.3.0
- r-reshape2=1.4.4
- r-reshape=0.8.8
- r-reticulate=1.15
- r-rex=1.2.0
- r-rgl=0.100.54
- r-rio=0.5.16
- r-rjson=0.2.20
- r-rlang=1.0.6
- r-rmarkdown=2.1
- r-rngtools=1.5
- r-robust=0.5_0.0
- r-robustbase=0.93_6
- r-rocr=1.0_7
- r-roxygen2=7.1.0
- r-rpart=4.1_15
- r-rprojroot=1.3_2
- r-rrcov=1.5_2
- r-rspectra=0.16_0
- r-rsqlite=2.2.0
- r-rstudioapi=0.11
- r-rsvd=1.0.3
- r-rtsne=0.15
- r-runit=0.4.32
- r-rvcheck=0.1.8
- r-rversions=2.0.1
- r-rvest=0.3.5
- r-sandwich=2.5_1
- r-scales=1.1.0
- r-scatterplot3d=0.3_41
- r-sctransform=0.2.1
- r-segmented=1.1_0
- r-selectr=0.4_2
- r-sendmailr=1.2_1
- r-seqinr=3.6_1
- r-sessioninfo=1.1.1
- r-seurat=3.1.5
- r-shape=1.4.4
- r-shiny=1.4.0.2
- r-shinyjs=1.1
- r-shinythemes=1.1.2
- r-sitmo=2.0.1
- r-slam=0.1_47
- r-snow=0.4_3
- r-sourcetools=0.1.7
- r-sp=1.4_1
- r-spam=2.5_1
- r-sparsem=1.78
- r-sparsesvd=0.2
- r-spatialextremes=2.0_8
- r-splus2r=1.2_2
- r-squarem=2020.2
- r-statmod=1.4.34
- r-stringi=1.4.3
- r-stringr=1.4.0
- r-subplex=1.6
- r-survival=3.1_12
- r-survminer=0.4.6
- r-survmisc=0.5.5
- r-svd=0.5
- r-svglite=1.2.3
- r-svmisc=1.1.0
- r-sys=3.3
- r-systemfonts=0.2.1
- r-testthat=2.3.2
- r-th.data=1.0_10
- r-tibble=3.0.1
- r-tidygraph=1.1.2
- r-tidyr=1.0.2
- r-tidyselect=1.1.2
- r-tidytree=0.3.3
- r-tidyverse=1.3.0
- r-timedate=3043.102
- r-tinytex=0.22
- r-truncnorm=1.0_8
- r-tsne=0.1_3
- r-ttr=0.23_6
- r-tweenr=1.0.1
- r-unix=1.5.4
- r-upsetr=1.4.0
- r-usethis=1.6.1
- r-utf8=1.1.4
- r-uuid=0.1_4
- r-uwot=0.1.8
- r-vctrs=0.4.1
- r-vegan=2.5_6
- r-venndiagram=1.6.20
- r-vgam=1.1_3
- r-vipor=0.4.5
- r-viridis=0.5.1
- r-viridislite=0.3.0
- r-webshot=0.5.2
- r-wgcna=1.68
- r-whisker=0.4
- r-withr=2.2.0
- r-xcell=1.2
- r-xfun=0.33
- r-xml2=1.3.2
- r-xml=3.99_0.3
- r-xopen=1.0.0
- r-xtable=1.8_4
- r-xts=0.12_0
- r-yaml=2.2.1
- r-zip=2.0.4
- r-zoo=1.8_7
- rdkit=2019.09.3
- re2=2022.06.01
- readline=7.0
- requests-kerberos=0.12.0
- requests=2.28.1
- retrying=1.3.3
- rfilepaths=0.4.0
- rinchi=1.0.0
- samtools=1.6
- scikit-image=0.17.2
- scikit-learn=0.24.2
- scipy=1.5.3
- seaborn=0.11.2
- setuptools=58.0.4
- singler=1.0
- sip=4.19.8
- six=1.16.0
- sls-logging=0.7.3
- snappy=1.1.9
- spectra=0.0.11
- sqlite=3.33.0
- star=2.7.10b
- suitesparse=5.10.1
- sysroot_linux-64=2.17
- tbb=2020.3
- threadpoolctl=3.1.0
- tifffile=2020.10.1
- tk=8.6.12
- tktable=2.10
- toolz=0.12.0
- tornado=6.1
- tqdm=4.64.1
- transforms=1.586.0
- typing=3.10.0.0
- umap-learn=0.4.6
- uriparser=0.9.5
- urllib3=1.26.11
- utf8proc=2.6.1
- wget=1.21.3
- wheel=0.37.1
- wrapt=1.13.1
- xorg-kbproto=1.0.7
- xorg-libice=1.0.10
- xorg-libsm=1.2.3
- xorg-libx11=1.7.2
- xorg-libxext=1.3.4
- xorg-libxpm=3.5.13
- xorg-libxrender=0.9.10
- xorg-libxt=1.2.1
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xz=5.2.6
- yaml=0.2.5
- zeroc-ice=3.6.5
- zlib=1.2.13
- zstd=1.4.5
name: legacy
