channels:
- bioconda
- conda-forge
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- abseil-cpp=20200225.2
- arrow-cpp=3.0.0
- binutils_impl_linux-64=2.31.1
- binutils_linux-64=2.31.1
- blas=1.0
- boost-cpp=1.73.0
- brotli-bin=1.0.9
- brotli=1.0.9
- brotlipy=0.7.0
- bwidget=1.9.11
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2022.07.19
- cairo=1.16.0
- certifi=2021.5.30
- cffi=1.14.0
- charset-normalizer=2.0.4
- conjure-python-client=1.10.1
- cryptography=35.0.0
- curl=7.68.0
- cycler=0.11.0
- dbus=1.13.18
- decorator=5.1.1
- dill=0.3.4
- double-conversion=3.1.5
- expat=2.4.8
- font-ttf-dejavu-sans-mono=2.37
- fontconfig=2.14.0
- freetype=2.11.0
- future=0.18.2
- gcc_impl_linux-64=7.3.0
- gcc_linux-64=7.3.0
- gettext=0.21.0
- gflags=2.2.2
- gfortran_impl_linux-64=7.3.0
- gfortran_linux-64=7.3.0
- glib-tools=2.70.2
- glib=2.70.2
- glog=0.5.0
- graphite2=1.3.14
- grpc-cpp=1.29.0
- gsl=2.5
- gst-plugins-base=1.14.0
- gstreamer=1.14.0
- gxx_impl_linux-64=7.3.0
- gxx_linux-64=7.3.0
- harfbuzz=2.8.1
- icu=58.2
- idna=3.3
- jedi=0.17.2
- jpeg=9e
- kiwisolver=1.3.1
- krb5=1.16.4
- ld_impl_linux-64=2.33.1
- libblas=3.9.0
- libboost=1.73.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libcurl=7.68.0
- libedit=3.1.20210910
- libevent=2.1.12
- libffi=3.4.2
- libgcc-ng=12.1.0
- libgcc=7.2.0
- libgfortran-ng=7.5.0
- libgfortran4=7.5.0
- libglib=2.70.2
- libgomp=12.1.0
- libiconv=1.16
- liblapack=3.9.0
- libopenblas=0.3.18
- libpng=1.6.37
- libprotobuf=3.11.4
- libssh2=1.10.0
- libstdcxx-ng=11.2.0
- libthrift=0.13.0
- libtiff=4.2.0
- libuuid=2.32.1
- libwebp-base=1.2.2
- libxcb=1.15
- libxml2=2.9.14
- libzlib=1.2.12
- lz4-c=1.9.3
- make=4.2.1
- matplotlib=2.2.3
- ncurses=6.3
- numpy-base=1.19.2
- numpy=1.19.2
- openssl=1.1.1
- orc=1.6.5
- packaging=21.3
- pandas=0.25.3
- pandoc=2.12
- pango=1.40.14
- parso=0.7.0
- pcre=8.45
- pip=21.2.2
- pixman=0.40.0
- py4j=0.10.9.7
- pyarrow=3.0.0
- pycparser=2.21
- pyopenssl=22.0.0
- pyparsing=3.0.4
- pyqt=5.9.2
- pysocks=1.7.1
- python-dateutil=2.8.2
- python=3.6.10
- python_abi=3.6
- pytz=2021.3
- pyyaml=5.4.1
- qt=5.9.7
- re2=2022.04.01
- readline=7.0
- requests=2.27.1
- setuptools=58.0.4
- sip=4.19.8
- six=1.16.0
- snappy=1.1.9
- sqlite=3.33.0
- tk=8.6.12
- tktable=2.10
- tornado=6.1
- typing=3.10.0.0
- uriparser=0.9.3
- urllib3=1.26.8
- utf8proc=2.6.1
- wheel=0.37.1
- wrapt=1.12.1
- xz=5.2.5
- yaml=0.2.5
- zlib=1.2.12
- zstd=1.4.5
name: bulk_rna_seq
