channels:
- bioconda
- conda-forge
- defaults
dependencies:
- bioconductor-complexheatmap==2.0.0
- bioconductor-edger==3.24.3
- bioconductor-fgsea==1.8.0
- bioconductor-genomeinfodbdata==1.2.1
- bioconductor-limma==3.38.3
- bioconductor-sva==3.30.1
- r-amap==0.8_16
- r-base==3.5.*
- r-biocmanager
- r-colorspace==1.4_1
- r-curl==4.3
- r-dendextend==1.13.4
- r-dendsort==0.3.3
- r-dplyr==0.8.5
- r-ggplot2==3.3.0
- r-ggrepel==0.8.2
- r-gplots==3.0.3
- r-gridextra==2.3
- r-gridgraphics==0.5_0
- r-heatmaply==1.1.0
- r-jsonlite=1.6.1
- r-l2p==0.0_13
- r-l2psupp==0.0_13
- r-magrittr=2.0.3
- r-markdown==1.1
- r-patchwork==1.0.0
- r-pheatmap==1.0.12
- r-plotly==4.9.2.1
- r-plotrix==3.7_8
- r-plyr==1.8.6
- r-rcolorbrewer==1.1_2
- r-renv
- r-renv==0.9.3
- r-reshape2==1.4.4
- r-reshape==0.8.8
- r-statmod==1.4.34
- r-stringr==1.4.0
- r-svglite==1.2.3
- r-tibble==3.0.1
- r-tidyverse==1.3.0
- r-upsetr==1.4.0
- r-venndiagram==1.6.20
name: bulk_rna_seq
