channels:
- bioconda
- conda-forge
- defaults
dependencies:
- _r-mutex=1.0.1
- r-abind=1.4_5
- r-acepack=1.4.1
- r-ade4=1.7_15
- r-amap=0.8_16
- r-ape=5.3
- r-arrow=3.0.0
- r-ashr=2.2_47
- r-askpass=1.1
- r-assertthat=0.2.1
- r-backports=1.2.1
- r-base64enc=0.1_3
- r-base=3.5.1
- r-batchjobs=1.8
- r-bbmisc=1.11
- r-bbmle=1.0.23.1
- r-bdsmatrix=1.3_4
- r-beeswarm=0.2.3
- r-bh=1.72.0_3
- r-bibtex=0.4.2.2
- r-bigl=1.2.3
- r-bio3d=2.4_1
- r-biocmanager
- r-biocmanager=1.30.10
- r-bit64=0.9_7
- r-bit=1.1_15.2
- r-bitops=1.0_6
- r-blob=1.2.1
- r-boot=1.3_25
- r-brew=1.0_6
- r-broom=0.5.6
- r-callr=3.4.3
- r-car=3.0_7
- r-cardata=3.0_3
- r-caret=6.0_86
- r-catools=1.17.1.4
- r-cellranger=1.1.0
- r-checkmate=2.0.0
- r-circlize=0.4.9
- r-class=7.3_17
- r-cli=3.4.1
- r-clipr=0.7.0
- r-cluster=2.1.0
- r-coda=0.19_3
- r-codetools=0.2_16
- r-colorramps=2.3
- r-colorspace=1.4_1
- r-colourpicker=1.0
- r-combinat=0.0_8
- r-cometexacttest=0.1.5
- r-commonmark=1.7
- r-corrplot=0.84
- r-covr=3.5.0
- r-cowplot=1.0.0
- r-crayon=1.3.4
- r-crosstalk=1.1.0.1
- r-curl=4.3
- r-data.table=1.12.8
- r-dbi=1.1.0
- r-dbplyr=1.4.3
- r-ddrtree=0.1.5
- r-dendextend=1.13.4
- r-dendsort=0.3.3
- r-densityclust=0.3
- r-deoptimr=1.0_8
- r-deriv=4.0
- r-desc=1.2.0
- r-desolve=1.28
- r-devtools=2.3.0
- r-dichromat=2.0_0
- r-digest=0.6.25
- r-docopt=0.6.1
- r-dofuture=0.9.0
- r-doparallel=1.0.15
- r-dotcall64=1.0_0
- r-downloader=0.4
- r-dplyr=0.8.5
- r-dppackage=1.1_7.4
- r-dqrng=0.2.1
- r-drc=3.0_1
- r-drugcombo=1.0.3
- r-dt=0.13
- r-dynamictreecut=1.63_1
- r-ellipsis=0.3.0
- r-emdbook=1.3.12
- r-etrunct=0.1
- r-evaluate=0.14
- r-exactranktests=0.8_31
- r-fansi=0.4.1
- r-farver=2.0.3
- r-fastcluster=1.1.25
- r-fastica=1.2_2
- r-fastmap=1.1.0
- r-fastmatch=1.1_0
- r-fields=10.3
- r-fit.models=0.5_14
- r-fitdistrplus=1.1_6
- r-fnn=1.1.3
- r-forcats=0.5.0
- r-foreach=1.5.0
- r-foreign=0.8_76
- r-formatr=1.7
- r-formula=1.2_3
- r-fs=1.5.2
- r-futile.logger=1.4.3
- r-futile.options=1.0.1
- r-future.apply=1.5.0
- r-future=1.17.0
- r-gbrd=0.4_11
- r-gdata=2.18.0
- r-gdtools=0.2.2
- r-geiger=2.0.6.4
- r-generics=0.0.2
- r-getoptlong=0.1.8
- r-ggally=1.5.0
- r-ggbeeswarm=0.6.0
- r-ggdendro=0.1_20
- r-ggextra=0.9
- r-ggforce=0.3.1
- r-ggfortify=0.4.10
- r-ggplot2=3.3.0
- r-ggpmisc=0.3.4
- r-ggpubr=0.2.5
- r-ggraph=2.0.2
- r-ggrepel=0.8.2
- r-ggridges=0.5.2
- r-ggsci=2.9
- r-ggsignif=0.6.0
- r-ggthemes=4.2.0
- r-gh=1.1.0
- r-git2r=0.26.1
- r-globaloptions=0.1.1
- r-globals=0.12.5
- r-glue=1.6.2
- r-gower=0.2.1
- r-gplots=3.0.3
- r-graphlayouts=0.7.0
- r-gridbase=0.4_7
- r-gridextra=2.3
- r-gridgraphics=0.5_0
- r-grimport=0.9_3
- r-gtable=0.3.0
- r-gtools=3.8.2
- r-harmony=1.0
- r-haven=2.2.0
- r-hdf5r=1.3.2
- r-hexbin=1.28.1
- r-highr=0.8
- r-hmisc=4.4_0
- r-hms=0.5.3
- r-htmltable=1.13.3
- r-htmltools=0.5.3
- r-htmlwidgets=1.5.1
- r-httpuv=1.5.2
- r-httr=1.4.1
- r-hwriter=1.3.2
- r-ica=1.0_2
- r-igraph=1.2.5
- r-ini=0.3.1
- r-invgamma=1.1
- r-ipred=0.9_9
- r-ips=0.0.11
- r-irlba=2.3.3
- r-isoband=0.2.1
- r-iterators=1.0.12
- r-jsonlite=1.6.1
- r-kernsmooth=2.23_17
- r-km.ci=0.5_2
- r-kmsurv=0.1_5
- r-knitr=1.28
- r-l2p=0.0_1
- r-labeling=0.3
- r-lambda.r=1.2.4
- r-later=1.0.0
- r-lattice=0.20_41
- r-latticeextra=0.6_28
- r-lava=1.6.7
- r-lazyeval=0.2.2
- r-leiden=0.3.3
- r-lifecycle=0.2.0
- r-listenv=0.8.0
- r-lme4=1.1_23
- r-lmertest=3.1_2
- r-lmtest=0.9_37
- r-locfit=1.5_9.4
- r-lubridate=1.7.8
- r-magrittr=2.0.3
- r-manipulatewidget=0.10.1
- r-maps=3.3.0
- r-maptools=0.9_9
- r-markdown=1.1
- r-mass=7.3_51.6
- r-matlab=1.0.2
- r-matrix=1.2_18
- r-matrixmodels=0.4_1
- r-matrixstats=0.56.0
- r-maxstat=0.7_25
- r-mclust=5.4.6
- r-memoise=1.1.0
- r-metap=1.1
- r-mgcv=1.8_31
- r-mime=0.9
- r-miniui=0.1.1.1
- r-minpack.lm=1.2_1
- r-minqa=1.2.4
- r-mixsqp=0.3_17
- r-modelmetrics=1.2.2.2
- r-modelr=0.1.7
- r-modes=0.7.0
- r-multcomp=1.4_13
- r-munsell=0.5.0
- r-mvtnorm=1.1_0
- r-ncbit=2013.03.29
- r-nleqslv=3.3.2
- r-nlme=3.1_147
- r-nloptr=1.2.2.1
- r-nmf=0.21.0
- r-nnet=7.3_14
- r-numderiv=2016.8_1.1
- r-openssl=1.4.1
- r-openxlsx=4.1.4
- r-outliers=0.14
- r-patchwork=1.0.0
- r-pbapply=1.4_2
- r-pbkrtest=0.4_7
- r-pbmcapply=1.5.0
- r-pcapp=1.9_73
- r-permute=0.9_5
- r-phangorn=2.5.5
- r-pheatmap=1.0.12
- r-pillar=1.4.3
- r-pixmap=0.4_11
- r-pkgbuild=1.0.7
- r-pkgconfig=2.0.3
- r-pkgload=1.0.2
- r-pkgmaker=0.31.1
- r-plogr=0.2.0
- r-plotly=4.9.2.1
- r-plotrix=3.7_8
- r-plyr=1.8.6
- r-png=0.1_7
- r-polyclip=1.10_0
- r-polynom=1.4_0
- r-pracma=2.2.9
- r-praise=1.0.0
- r-prettyunits=1.1.1
- r-proc=1.16.2
- r-processx=3.4.2
- r-prodlim=2019.11.13
- r-progress=1.2.2
- r-promises=1.1.0
- r-proxy=0.4_24
- r-pryr=0.1.4
- r-ps=1.3.2
- r-purrr=0.3.4
- r-qlcmatrix=0.9.7
- r-qtl=1.46_2
- r-quadprog=1.5_8
- r-quantmod=0.4.17
- r-quantreg=5.55
- r-r.methodss3=1.8.0
- r-r.oo=1.23.0
- r-r.utils=2.9.2
- r-r6=2.4.1
- r-randomforest=4.6_14
- r-rann=2.6.1
- r-rappdirs=0.3.1
- r-rcmdcheck=1.3.3
- r-rcolorbrewer=1.1_2
- r-rcpp=1.0.6
- r-rcppannoy=0.0.16
- r-rcpparmadillo=0.9.870.2.0
- r-rcppeigen=0.3.3.7.0
- r-rcppnumerical=0.4_0
- r-rcppparallel=5.1.5
- r-rcppprogress=0.4.2
- r-rcurl=1.98_1.2
- r-rdpack=0.11_1
- r-readr=1.3.1
- r-readxl=1.3.1
- r-recipes=0.1.12
- r-registry=0.5_1
- r-rematch2=2.1.2
- r-rematch=1.0.1
- r-remotes=2.1.1
- r-renv
- r-reprex=0.3.0
- r-reshape2=1.4.4
- r-reshape=0.8.8
- r-reticulate=1.15
- r-rex=1.2.0
- r-rgl=0.100.54
- r-rio=0.5.16
- r-rjson=0.2.20
- r-rlang=1.0.6
- r-rmarkdown=2.1
- r-rngtools=1.5
- r-robust=0.5_0.0
- r-robustbase=0.93_6
- r-rocr=1.0_7
- r-roxygen2=7.1.0
- r-rpart=4.1_15
- r-rprojroot=1.3_2
- r-rrcov=1.5_2
- r-rspectra=0.16_0
- r-rsqlite=2.2.0
- r-rstudioapi=0.11
- r-rsvd=1.0.3
- r-rtsne=0.15
- r-runit=0.4.32
- r-rvcheck=0.1.8
- r-rversions=2.0.1
- r-rvest=0.3.5
- r-sandwich=2.5_1
- r-scales=1.1.0
- r-scatterplot3d=0.3_41
- r-sctransform=0.2.1
- r-segmented=1.1_0
- r-selectr=0.4_2
- r-sendmailr=1.2_1
- r-seqinr=3.6_1
- r-sessioninfo=1.1.1
- r-seurat=3.1.5
- r-shape=1.4.4
- r-shiny=1.4.0.2
- r-shinyjs=1.1
- r-shinythemes=1.1.2
- r-sitmo=2.0.1
- r-slam=0.1_47
- r-snow=0.4_3
- r-sourcetools=0.1.7
- r-sp=1.4_1
- r-spam=2.5_1
- r-sparsem=1.78
- r-sparsesvd=0.2
- r-spatialextremes=2.0_8
- r-splus2r=1.2_2
- r-squarem=2020.2
- r-statmod=1.4.34
- r-stringi=1.4.3
- r-stringr=1.4.0
- r-subplex=1.6
- r-survival=3.1_12
- r-survminer=0.4.6
- r-survmisc=0.5.5
- r-svd=0.5
- r-svglite=1.2.3
- r-svmisc=1.1.0
- r-sys=3.3
- r-systemfonts=0.2.1
- r-testthat=2.3.2
- r-th.data=1.0_10
- r-tibble=3.0.1
- r-tidygraph=1.1.2
- r-tidyr=1.0.2
- r-tidyselect=1.1.2
- r-tidytree=0.3.3
- r-tidyverse=1.3.0
- r-timedate=3043.102
- r-tinytex=0.22
- r-truncnorm=1.0_8
- r-tsne=0.1_3
- r-ttr=0.23_6
- r-tweenr=1.0.1
- r-unix=1.5.4
- r-upsetr=1.4.0
- r-usethis=1.6.1
- r-utf8=1.1.4
- r-uuid=0.1_4
- r-uwot=0.1.8
- r-vctrs=0.4.1
- r-vegan=2.5_6
- r-venndiagram=1.6.20
- r-vgam=1.1_3
- r-vipor=0.4.5
- r-viridis=0.5.1
- r-viridislite=0.3.0
- r-webshot=0.5.2
- r-wgcna=1.68
- r-whisker=0.4
- r-withr=2.2.0
- r-xcell=1.2
- r-xfun=0.33
- r-xml2=1.3.2
- r-xml=3.99_0.3
- r-xopen=1.0.0
- r-xtable=1.8_4
- r-xts=0.12_0
- r-yaml=2.2.1
- r-zip=2.0.4
- r-zoo=1.8_7
name: legacy
