channels:
- bioconda
- conda-forge
- defaults
dependencies:
- _r-mutex=1.0.1
- r-amap=0.8_16
- r-arrow=3.0.0
- r-askpass=1.1
- r-assertthat=0.2.1
- r-backports=1.2.1
- r-base64enc=0.1_3
- r-base=3.5.1
- r-bh=1.72.0_3
- r-bit64=0.9_7
- r-bit=1.1_15.2
- r-bitops=1.0_6
- r-blob=1.2.1
- r-broom=0.5.6
- r-callr=3.4.3
- r-catools=1.17.1.4
- r-cellranger=1.1.0
- r-circlize=0.4.9
- r-cli=2.0.2
- r-clipr=0.7.0
- r-clue=0.3_57
- r-cluster=2.1.0
- r-codetools=0.2_16
- r-colorspace=1.4_1
- r-crayon=1.3.4
- r-crosstalk=1.0.0
- r-curl=4.3
- r-data.table=1.11.6
- r-dbi=1.1.0
- r-dbplyr=1.4.3
- r-dendextend=1.13.4
- r-dendsort=0.3.3
- r-desc=1.2.0
- r-digest=0.6.25
- r-dplyr=0.8.5
- r-egg=0.4.5
- r-ellipsis=0.3.0
- r-evaluate=0.14
- r-fansi=0.4.1
- r-farver=2.0.3
- r-fastmap=1.0.1
- r-fastmatch=1.1_0
- r-forcats=0.5.0
- r-foreach=1.5.0
- r-formatr=1.7
- r-fs=1.4.1
- r-futile.logger=1.4.3
- r-futile.options=1.0.1
- r-gclus=1.3.1
- r-gdata=2.18.0
- r-gdtools=0.2.2
- r-generics=0.0.2
- r-getoptlong=0.1.8
- r-ggplot2=3.3.0
- r-ggrepel=0.8.2
- r-globaloptions=0.1.1
- r-glue=1.6.2
- r-gplots=3.0.3
- r-gridextra=2.3
- r-gridgraphics=0.5_0
- r-gtable=0.3.0
- r-gtools=3.8.2
- r-haven=2.2.0
- r-heatmaply=1.1.0
- r-hexbin=1.28.1
- r-highr=0.8
- r-hms=0.5.3
- r-htmltools=0.4.0
- r-htmlwidgets=1.5.1
- r-httpuv=1.5.2
- r-httr=1.4.1
- r-isoband=0.2.1
- r-iterators=1.0.12
- r-kernsmooth=2.23_17
- r-knitr=1.28
- r-labeling=0.3
- r-lambda.r=1.2.4
- r-later=1.0.0
- r-lattice=0.20_41
- r-lazyeval=0.2.2
- r-lifecycle=0.2.0
- r-locfit=1.5_9.4
- r-lubridate=1.7.8
- r-markdown=1.1
- r-mass=7.3_51.6
- r-matrix=1.2_18
- r-matrixstats=0.56.0
- r-memoise=1.1.0
- r-mgcv=1.8_31
- r-mime=0.9
- r-modelr=0.1.7
- r-munsell=0.5.0
- r-nlme=3.1_147
- r-openssl=1.4.1
- r-patchwork=1.0.0
- r-pheatmap=1.0.12
- r-pillar=1.4.3
- r-pkgbuild=1.0.7
- r-pkgconfig=2.0.1
- r-pkgload=1.0.2
- r-plogr=0.2.0
- r-plotly=4.9.2.1
- r-plotrix=3.7_8
- r-plyr=1.8.6
- r-png=0.1_7
- r-praise=1.0.0
- r-prettyunits=1.1.1
- r-processx=3.4.2
- r-progress=1.2.2
- r-promises=1.1.0
- r-ps=1.3.2
- r-purrr=0.3.4
- r-qap=0.1_1
- r-r6=2.4.1
- r-rcolorbrewer=1.1_2
- r-rcpp=1.0.6
- r-rcurl=1.98_1.2
- r-readr=1.3.1
- r-readxl=1.3.1
- r-registry=0.5_1
- r-rematch=1.0.1
- r-renv=0.9.3
- r-reprex=0.3.0
- r-reshape2=1.4.4
- r-reshape=0.8.8
- r-rjson=0.2.20
- r-rlang=0.4.10
- r-rmarkdown=2.1
- r-rprojroot=1.3_2
- r-rsqlite=2.2.0
- r-rstudioapi=0.11
- r-rvest=0.3.5
- r-scales=1.1.0
- r-selectr=0.4_2
- r-seriation=1.2_2
- r-shape=1.4.4
- r-shiny=1.4.0.2
- r-snow=0.4_3
- r-sourcetools=0.1.7
- r-statmod=1.4.34
- r-stringi=1.4.3
- r-stringr=1.4.0
- r-survival=3.1_12
- r-svglite=1.2.3
- r-svmisc=1.1.0
- r-sys=3.3
- r-systemfonts=0.2.1
- r-testthat=2.3.2
- r-tibble=3.0.1
- r-tidyr=1.0.2
- r-tidyselect=1.0.0
- r-tidyverse=1.3.0
- r-tinytex=0.22
- r-tsp=1.1_5
- r-unix=1.5.4
- r-upsetr=1.4.0
- r-utf8=1.1.4
- r-uuid=0.1_4
- r-vctrs=0.2.4
- r-venndiagram=1.6.20
- r-viridis=0.5.1
- r-viridislite=0.3.0
- r-webshot=0.5.2
- r-whisker=0.4
- r-withr=2.2.0
- r-xfun=0.13
- r-xml2=1.3.2
- r-xml=3.99_0.3
- r-xtable=1.8_4
- r-yaml=2.2.1
- r-zeallot=0.1.0
name: bulk_rna_seq
