name: Build_and_upload_docker
run-name: ${{ github.actor }} is generating NAMESPACE file
on:
  release:
    types: [published]
jobs:
  Build-img-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "Running test in DSP docker container"
      - uses: actions/checkout@v3
      
      - name: Build-image
        run: docker build --file Dockerfile --tag legacy_default:$(date) .
        
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: legacy_default:$(date)
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
